spring:
  application:
    name: events
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: dba
    password: dba
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    vault:
      enabled: false
  jackson:
    deserialization:
      FAIL_ON_NULL_FOR_PRIMITIVES: true